apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
  labels:
    app: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
      - name: portainer
        image: portainer/portainer-ce:latest
        ports:
        - containerPort: 9000
          name: http
        - containerPort: 8000
          name: edge
        env:
        - name: PORTAINER_ADMIN_PASSWORD
          value: "admin"
        - name: PORTAINER_ADMIN_PASSWORD_HASH
          value: "$2a$05$IxQ2H3Yj5zSYbA5p1YqpuOYg/8KwxYpF7YV1J9Kc9J9Kc9J9Kc9J9K"
        - name: PORTAINER_SECURITY_TIMEOUT
          value: "0"
        - name: PORTAINER_SECURITY_TIMEOUT_ENABLED
          value: "false"
        - name: PORTAINER_EDGE
          value: "0"
        - name: PORTAINER_EDGE_INSECURE_POLL
          value: "0"
        - name: PORTAINER_BASE_URL
          value: "/portainer"
        - name: PORTAINER_SERVE_FROM_SUBPATH
          value: "true"
        - name: PORTAINER_HOST
          value: "portainer.default.svc.cluster.local"
        - name: PORTAINER_ADMIN_USERNAME
        volumeMounts:
        - name: portainer-data
          mountPath: /data
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: portainer-data
        persistentVolumeClaim:
          claimName: portainer-pvc
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock 