apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: portainer
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods", "nodes", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer
subjects:
- kind: ServiceAccount
  name: portainer
  namespace: default
roleRef:
  kind: ClusterRole
  name: portainer
  apiGroup: rbac.authorization.k8s.io 