apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-service-config
data:
  NODE_ENV: "production"
  PORT: "3003"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/courses_db" 