apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  labels:
    app: ingestion-service
spec:
  selector:
    app: ingestion-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP 