apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  VITE_API_URL: "http://188.245.104.79/api"
  VITE_AUTH_SERVICE_URL: "http://188.245.104.79/auth"
  VITE_COURSE_SERVICE_URL: "http://188.245.104.79/courses"
  VITE_BASE_URL: "/frontend"
  VITE_SERVE_FROM_SUBPATH: "true"
  VITE_PORT: "3000" 