apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres
  - pgadmin
  - auth-service
  - course-service
  - ingestion-service
  - kong
  - portainer
  - frontend
  - monitoring 