apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config-file
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true

    plugins:
      - name: cors
        config:
          origins: ['*']
          methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
          headers: ['Accept', 'Accept-Version', 'Content-Length', 'Content-MD5', 'Content-Type', 'Date', 'Authorization']
          exposed_headers: ['X-Auth-Token']
          credentials: true
          max_age: 3600

    services:
      - name: frontend
        url: http://frontend:3000
        routes:
          - name: frontend-route
            paths:
              - /frontend
              - /
            strip_path: true
            preserve_host: true
          - name: frontend-catchall
            paths:
              - /~
            strip_path: false
            preserve_host: true

      - name: auth-service
        url: http://auth-service:3001
        routes:
          - name: auth-route
            paths:
              - /auth
            strip_path: true
            preserve_host: true

      - name: course-service
        url: http://course-service:3002
        routes:
          - name: course-route
            paths:
              - /courses
            strip_path: true
            preserve_host: true

      - name: ingestion-service
        url: http://ingestion-service:3003
        routes:
          - name: ingestion-route
            paths:
              - /ingestion
            strip_path: true
            preserve_host: true

      - name: metrics
        url: http://kong-admin.default.svc.cluster.local:8001
        routes:
          - name: metrics-route
            paths:
              - /metrics
            strip_path: false
            preserve_host: true
            protocols:
              - http
            path_handling: "v0"

      - name: grafana
        url: http://grafana.monitoring.svc.cluster.local:3000
        routes:
          - name: grafana-route
            paths:
              - /grafana
            strip_path: false
            preserve_host: true
            protocols:
              - http
            path_handling: "v0"

      - name: prometheus
        url: http://prometheus.monitoring.svc.cluster.local:9090
        routes:
          - name: prometheus-route
            paths:
              - /prometheus
            strip_path: false
            preserve_host: true
            protocols:
              - http
            path_handling: "v0"

      - name: argocd-server
        url: http://argocd-server.argocd:80
        routes:
          - name: argocd-route
            paths:
              - /argo
            strip_path: true
            preserve_host: true

      - name: pgadmin
        url: http://pgadmin:80
        routes:
          - name: pgadmin-route
            paths:
              - /pgadmin
            strip_path: true
            preserve_host: true

      - name: portainer
        url: http://portainer:9000
        routes:
          - name: portainer-route
            paths:
              - /portainer
            strip_path: true
            preserve_host: true
            headers:
              - X-Forwarded-Proto: http
              - X-Forwarded-Host: 188.245.104.79 