apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  KONG_DATABASE: "off"
  KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
  KONG_DNS_ORDER: "LAST,A,CNAME"
  KONG_PLUGINS: "bundled"
  KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  KONG_PROXY_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  KONG_PROXY_LISTEN: "0.0.0.0:8000"
  KONG_STREAM_LISTEN: "off"
  KONG_SSL_LISTEN: "off"
  KONG_PROXY_READ_TIMEOUT: "60000"
  KONG_PROXY_SEND_TIMEOUT: "60000"
  KONG_PROXY_CONNECT_TIMEOUT: "60000"
  KONG_PROXY_KEEPALIVE: "60000"
  KONG_PROXY_KEEPALIVE_REQUESTS: "1000"
  KONG_PROXY_KEEPALIVE_TIMEOUT: "60"
  KONG_NGINX_PROXY_PROXY_READ_TIMEOUT: "60s"
  KONG_NGINX_PROXY_PROXY_SEND_TIMEOUT: "60s"
  KONG_NGINX_PROXY_PROXY_CONNECT_TIMEOUT: "60s"
  KONG_NGINX_PROXY_KEEPALIVE_TIMEOUT: "60s"
  KONG_NGINX_PROXY_KEEPALIVE_REQUESTS: "1000"
  KONG_NGINX_DAEMON: "off"
  KONG_LOG_LEVEL: "debug"
  KONG_PROXY_LISTEN_SSL: "off"
  KONG_ADMIN_LISTEN_SSL: "off"
  KONG_SSL: "off"
  KONG_DNS_RESOLVER: "10.96.0.10:53"
  KONG_DNS_HOSTSFILE: "/etc/hosts"
  KONG_DNS_ORDER: "LAST,A,CNAME"
  KONG_DNS_STRATEGY: "first"
  KONG_DNS_NO_SYNC: "off"
  KONG_DNS_ERROR_TTL: "1"
  KONG_DNS_CACHE_SIZE: "10000"
  KONG_DNS_STALE_TTL: "4"
  KONG_DNS_NOT_FOUND_TTL: "30" 