apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
type: Opaque
data:
  KONG_ADMIN_GUI_AUTH: YWRtaW46YWRtaW4=  # base64 encoded 'admin:admin'
  KONG_ADMIN_GUI_SESSION_CONF: eyJzZWNyZXQiOiJzZWNyZXQiLCJjb29raWUiOiJzZXNzaW9uIn0=  # base64 encoded '{"secret":"secret","cookie":"session"}' 