apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  type: NodePort
  ports:
    - name: proxy
      port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
    - name: admin
      port: 8001
      targetPort: 8001
      nodePort: 30081
      protocol: TCP
  selector:
    app: kong 