apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  selector:
    app: kong
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    nodePort: 30443
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  type: NodePort 