apiVersion: v1
kind: Service
metadata:
  name: kong
  labels:
    app: kong
spec:
  selector:
    app: kong
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    nodePort: 80
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    nodePort: 443
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    nodePort: 8001
    protocol: TCP
  - name: admin-ssl
    port: 8444
    targetPort: 8444
    nodePort: 8444
    protocol: TCP
  type: NodePort
  externalIPs:
    - 188.245.104.79 