apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: default
data:
  PGADMIN_CONFIG_SERVER_MODE: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "True"
  PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
  PGADMIN_CONFIG_MAIL_SERVER_ENABLED: "False"
  PGADMIN_CONFIG_LOGIN_BANNER: "Welcome to pgAdmin 4"
  PGADMIN_CONFIG_SESSION_TIMEOUT: "3600"
  PGADMIN_CONFIG_MAX_CONNECTION_IDLE_TIME: "600"
  PGADMIN_CONFIG_MAX_CONNECTION_LIFETIME: "3600"
  PGADMIN_CONFIG_POOL_RECYCLE: "3600"
  PGADMIN_CONFIG_POOL_SIZE: "10"
  PGADMIN_CONFIG_POOL_TIMEOUT: "30"
  PGADMIN_CONFIG_BASE_URL: "/pgadmin"
  PGADMIN_CONFIG_SERVE_FROM_SUBPATH: "True"
  PGADMIN_CONFIG_MASTER_PASSWORD_FILE: "/pgadmin4/pgadmin4.db" 