apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secrets
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=  # base64 encoded 'admin@example.com'
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=                # base64 encoded 'admin' 