apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: ClusterIP
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
  selector:
    app: pgadmin 