apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9hdXRoX2Ri
  JWT_SECRET: c2VjcmV0
  JWT_EXPIRES_IN: MWQ= 