apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvYXV0aF9kYg==
  JWT_SECRET: c2VjcmV0
  JWT_EXPIRES_IN: MWQ= 