apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
data:
  NODE_ENV: "production"
  PORT: "3002"
  INGESTION_SERVICE_URL: "http://ingestion-service:3003"
  AUTH_SERVICE_URL: "http://auth-service:3001" 