apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init-databases.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE courses_db;
    
    \c auth_db
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    
    \c courses_db
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; 