apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=      # base64 encoded 'postgres'
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # base64 encoded 'postgres'
  POSTGRES_DB: YXV0aF9kYg==        # base64 encoded 'auth_db'
  AUTH_DB_USER: YXV0aF91c2Vy        # base64 encoded 'auth_user'
  AUTH_DB_PASSWORD: YXV0aF9wYXNz    # base64 encoded 'auth_pass'
  COURSES_DB_USER: Y291cnNlc191c2Vy  # base64 encoded 'courses_user'
  COURSES_DB_PASSWORD: Y291cnNlc19wYXNz  # base64 encoded 'courses_pass' 