name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./auth-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/auth-service:latest

      - name: Build and push course-service
        uses: docker/build-push-action@v4
        with:
          context: ./course-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/course-service:latest

      - name: Build and push ingestion-service
        uses: docker/build-push-action@v4
        with:
          context: ./ingestion-service
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ingestion-service:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Pull latest images
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/auth-service:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/course-service:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/ingestion-service:latest
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest

            # Update services
            docker stack deploy -c docker/docker-compose.yml e-learning 